blog/urls.py
from django.urls import path, include
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.all_blogs, name='all_blogs'),
    path('<int:blog_id>/', views.detail, name='detail'),
]

exchange_rate/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from exchange_rate import views
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('exchange_rate/', views.index, name='index'),
    #path('about/', views.about, name='about'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio_site/urls.py
from django.contrib import admin
from django.urls import path, include
from portfolio import views 
#from quote_generator import views
#from exchange_rate import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    #path('about/', views.about, name='about'),
    path('blogs/', include('blog.urls')),
    #path('exchange_rate/', views.index, name='index'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.
class Blog(models.Model):
    title = models.CharField(max_length=150)
    description = models.TextField()
    date = models.DateField()
    
    def __str__(self):
        return self.title

exchange_rate/models.py
from django.db import models

# Create your models here.

portfolio/models.py
from django.db import models

# Create your models here.

class Project(models.Model):
    title = models.CharField(max_length = 50)
    desctription = models.CharField(max_length = 200)
    image = models.ImageField(upload_to = 'portfolio/images/')
    url =  models.URLField(blank = True)
    
    def __str__(self):
        return self.title
    

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog
# Create your views here.

def all_blogs(request):
    #blog_count = Blog.objects.count
    blogs = Blog.objects.order_by('-date')
    return render(request, 'blog/all_blogs.html', {'blogs': blogs})

def detail(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    return render(request, 'blog/detail.html', {'blog': blog})

exchange_rate/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.


def index(request):
    return render(request, 'exchange_rate/index.html')

portfolio/views.py
from django.shortcuts import render
from .models import Project

# Create your views here.
def home(request):
    projects = Project.objects.all()
    return render(request, 'portfolio/home.html', {'projects': projects})

quote_generator/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.


def index(request):
    return render(request, 'quote_generator/index.html')

def about(request):
    return render(request, 'quote_generator/about.html')

blog/templates/blog/all_blogs.html
{% extends 'portfolio/base.html' %}

{% block content %}

<h1>Blogs</h1>

<h2> I have writen {{ blogs.count }} blog{{ blogs.count|pluralize }} </h2>

{% for blog in blogs %}

    <a href="{% url 'blog:detail' blog.id %}"><h2>{{ blog.title }}</h2></a>
    <h5>{{ blog.date|date:'M d Y' }}</h5>
    <p>{{ blog.description|striptags|truncatechars:100 }}</p>
    
{% endfor %}

{% endblock %}

blog/templates/blog/details.html
{% extends 'portfolio/base.html' %}

{% block content %}

<br>

<h1>{{ blog.title }}</h1>

<h2>--- {{ blog.date|date:'F jS Y' }} ---</h2>

{{ blog.description|safe }}

{% endblock %}

exchange_rate/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Exchange Rate Calculator</title>
    <link rel="stylesheet" href= "{% static exchangerate/'style.css' %}" />
    <link rel="icon" type="image/png" href="{% static exchangerate/'favicon.png' %}">
</head>
<body>
    <img src="img/money.png" alt="" class="money-img"/>
    <h1>Exchange Rate Calculator</h1>
    <p>Choose the currency and the amounts to get the exchange rate</p>

    <div class = "container">
        <div class="currency">
            <select id="currency-one">
                <option value = "AED">AED</option>
                <option value = "ARS">ARS</option>
                <option value = "AUD">AUD</option>
                <option value = "BGN">BGN</option>
                <option value = "BRL">BRL</option>
                <option value = "BSD">BSD</option>
                <option value = "CAD">CAD</option>
                <option value = "CHF">CHF</option>
                <option value = "CLP">CLP</option>
                <option value = "CNY">CNY</option>
                <option value = "COP">COP</option>
                <option value = "CZK">CZK</option>
                <option value = "DKK">DKK</option>
                <option value = "DOP">DOP</option>
                <option value = "EGP">EGP</option>
                <option value = "EUR">EUR</option>
                <option value = "FDJ">FDJ</option>
                <option value = "GBP">GBP</option>
                <option value = "GTQ">GTQ</option>
                <option value = "HKD">HKD</option>
                <option value = "HRK">HRK</option>
                <option value = "HUF">HUF</option>
                <option value = "IDR">IDR</option>
                <option value = "ILS">ILS</option>
                <option value = "INR">INR</option>
                <option value = "ISK">ISK</option>
                <option value = "JPY">JPY</option>
                <option value = "KRW">KRW</option>
                <option value = "KZT">KZT</option>
                <option value = "MXN">MXN</option>
                <option value = "MYR">MYR</option>
                <option value = "NOK">NOK</option>
                <option value = "NZD">NZD</option>
                <option value = "PAB">PAB</option>
                <option value = "PEN">PEN</option>
                <option value = "PHP">PHP</option>
                <option value = "PKR">PKR</option>
                <option value = "PLN">PLN</option>
                <option value = "PYG">PYG</option>
                <option value = "RON">RON</option>
                <option value = "RUB">RUB</option>
                <option value = "SAR">SAR</option>
                <option value = "SEK">SEK</option>
                <option value = "SGD">SGD</option>
                <option value = "THB">THB</option>
                <option value = "TRY">TRY</option>
                <option value = "TWD">TWD</option>
                <option value = "UAH">UAH</option>
                <option value = "USD" selected>USD</option>
                <option value = "UYU">UYU</option>
                <option value = "VND">VND</option>
                <option value = "ZAR">ZAR</option>
            </select>
            <input type="number" id="amount-one" placeholder="0" value="1" />
        </div>

        <div class="swap-rate-container">
            <button class="btn" id="swap">
                Swap
            </button>
            <div class="rate" id="rate"></div>
        </div>

            <div class="currency">
                <select id="currency-two">
                    <option value = "AED">AED</option>
                    <option value = "ARS">ARS</option>
                    <option value = "AUD">AUD</option>
                    <option value = "BGN">BGN</option>
                    <option value = "BRL">BRL</option>
                    <option value = "BSD">BSD</option>
                    <option value = "CAD">CAD</option>
                    <option value = "CHF">CHF</option>
                    <option value = "CLP">CLP</option>
                    <option value = "CNY">CNY</option>
                    <option value = "COP">COP</option>
                    <option value = "CZK">CZK</option>
                    <option value = "DKK">DKK</option>
                    <option value = "DOP">DOP</option>
                    <option value = "EGP">EGP</option>
                    <option value = "EUR" selected>EUR</option>
                    <option value = "FDJ">FDJ</option>
                    <option value = "GBP">GBP</option>
                    <option value = "GTQ">GTQ</option>
                    <option value = "HKD">HKD</option>
                    <option value = "HRK">HRK</option>
                    <option value = "HUF">HUF</option>
                    <option value = "IDR">IDR</option>
                    <option value = "ILS">ILS</option>
                    <option value = "INR">INR</option>
                    <option value = "ISK">ISK</option>
                    <option value = "JPY">JPY</option>
                    <option value = "KRW">KRW</option>
                    <option value = "KZT">KZT</option>
                    <option value = "MXN">MXN</option>
                    <option value = "MYR">MYR</option>
                    <option value = "NOK">NOK</option>
                    <option value = "NZD">NZD</option>
                    <option value = "PAB">PAB</option>
                    <option value = "PEN">PEN</option>
                    <option value = "PHP">PHP</option>
                    <option value = "PKR">PKR</option>
                    <option value = "PLN">PLN</option>
                    <option value = "PYG">PYG</option>
                    <option value = "RON">RON</option>
                    <option value = "RUB">RUB</option>
                    <option value = "SAR">SAR</option>
                    <option value = "SEK">SEK</option>
                    <option value = "SGD">SGD</option>
                    <option value = "THB">THB</option>
                    <option value = "TRY">TRY</option>
                    <option value = "TWD">TWD</option>
                    <option value = "UAH">UAH</option>
                    <option value = "USD">USD</option>
                    <option value = "UYU">UYU</option>
                    <option value = "VND">VND</option>
                    <option value = "ZAR">ZAR</option>
                </select>
                <input type="number" id="amount-two" placeholder="0" />
            </div>
        </div>

        <script src="script.js"></script>
</body>
</html>

portfolio/templates/portfolio/base.html
{% load static %}

  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static "portfolio/custom.css" %}">

    <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">

    <!--link rel="icon" type="image/png" href="{% static "portfolio/logo.png" %}/"-->

    <title>Portfolio Site</title>
  
  </head>
  <body>

    <nav id="topNav" class="navbar navbar-expand-md navbar-light">
        <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}"> 
        <!--img src="{% static 'portfolio/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="Logo"-->
        <span>Gabriel Tejada</span></a>
    
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        
        <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse text-center" id="navbarNav">
            <ul class="navbar-nav ml-auto">
            <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
            </li>
            
            <li class="nav-item">
        
            <a class="nav-link" href="{% url 'blog:all_blogs' %}">Blog</a>
            </li>

            </ul>
        
        </div>
    </nav>

    {% block content %}{% endblock %}


    <!-- Option 1: Bootstrap Bundle with Popper -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>

  

portfolio/templates/portfolio/home.html
{% extends 'portfolio/base.html' %}

{% block content %}

{% load static %}

<div class="row justify-content-center my-3">
    <div class="col-5">
        <!--img src="{% static 'portfolio/main.jpg' %}" width="300" height="300" class="img-fluid"-->
    </div>
</div>

<div class="row justify-content-center mb-2">
    <div class="col-md-9 text-center">
      <h1 id="hometext" class="font-weight-bold">Gabriel Tejada</h1>
    </div>
  </div>

  <h2 class="mt-5">Portfolio</h2>

<hr>
<div class="row">
  {% for project in projects %}
  <div class="col-lg-4 col-md-6">

    {% if project.url %}
    <a href="{{ project.url }}">
      <img src="{{ project.image.url }}" class="img-fluid mb-2">
    </a>
    {% else %}

    <img src="{{ project.image.url }}" class="img-fluid mb-2">
    {% endif %}
    <h3>{{ project.title }}</h3>
    <p>{{ project.description }}</p>

  </div>
  {% endfor %}
</div>

{% endblock %}

quote_generator/templates/quote_generator/index.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Template</title>
    <link rel="icon" type="image/png" href="{% static 'favicon.png' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.2/css/all.min.css"/>
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
    <div class="quote-container" id="quote-container">
        <!-- Quote -->
        <div class="quote-text">
            <i class="fas fa-quote-left"></i>
            <span id="quote"></span>
        </div>
        <!-- Author -->
        <div class="quote-author">
            <span id="author"></span>
        </div>
        <!-- Buttons -->
        <div class="button-container">
            <button class="twitter-button" id="twitter" title="Tweet This!">
                <i class="fab fa-twitter"></i>
            </button>
            <button id="new-quote">New Quote</button>
        </div>
    </div>
    <!-- Loader -->
    <div class="loader" id="loader"></div>
    <!-- Script -->
    <script src="{% static 'quotes.js' %}"></script>
    <script src="{% static 'script.js' %}"></script>

    <!-- Script -->
    <script src="{% static 'script.js' %}"></script>
</body>
</html>